#MESSAGE( "External project - OpenCV" )

SET( LibZip_DEPENDENCIES )

SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_CXX_STANDARD_REQUIRED YES) 

SET( EXTRA_NON_WINDOWS_OPTIONS "")
IF(NOT WIN32)
SET( EXTRA_NON_WINDOWS_OPTIONS -DCMAKE_BUILD_TYPE=Release)
ENDIF()

MESSAGE( STATUS "Adding LibZip-1.5.2a ...")

ExternalProject_Add( 
  LibZip
  DEPENDS BZip2 ZLib
  GIT_REPOSITORY https://github.com/nih-at/libzip #  url from where to download
  SOURCE_DIR LibZip-source
  BINARY_DIR LibZip-build
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  INSTALL_COMMAND cmake -E echo "Skipping install step."
  CMAKE_GENERATOR ${gen}
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX:STRING=${PROJECT_BINARY_DIR}
    # -DINSTALL_BIN_DIR:STRING=${PROJECT_BINARY_DIR}/bin
    # -DINSTALL_INC_DIR:STRING=${PROJECT_BINARY_DIR}/include
    # -DINSTALL_LIB_DIR:STRING=${PROJECT_BINARY_DIR}/lib
    # -DINSTALL_MAN_DIR:STRING=${PROJECT_BINARY_DIR}/share/man
    # -DINSTALL_PKGCONFIG_DIR:STRING=${PROJECT_BINARY_DIR}/share/pkgconfig
    -DCMAKE_BUILD_TYPE:STRING=Release
)

SET( LibZip_DIR ${CMAKE_BINARY_DIR}/LibZip-build )
#LIST(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/OpenCV-build")
SET( ENV{CMAKE_PREFIX_PATH} "${CMAKE_PREFIX_PATH};${CMAKE_BINARY_DIR}/LibZip-build" )