#MESSAGE( "External project - OpenCV" )

SET( BZip2_DEPENDENCIES )

SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_CXX_STANDARD_REQUIRED YES) 

SET( EXTRA_NON_WINDOWS_OPTIONS "")
IF(NOT WIN32)
SET( EXTRA_NON_WINDOWS_OPTIONS -DCMAKE_BUILD_TYPE=Release)
ENDIF()

MESSAGE( STATUS "Adding BZip2-1.0.6 ...")

ExternalProject_Add( 
  BZip2
  GIT_REPOSITORY https://github.com/sergiud/bzip2 #  url from where to download
  SOURCE_DIR BZip2-source
  BINARY_DIR BZip2-build
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  INSTALL_COMMAND cmake -E echo "Skipping install step."
  CMAKE_GENERATOR ${gen}
  CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX:STRING=${PROJECT_BINARY_DIR}
  -DCMAKE_BUILD_TYPE:STRING=Release
)

SET( BZip2_DIR ${CMAKE_BINARY_DIR}/BZip2-build )
#LIST(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/OpenCV-build")
SET( ENV{CMAKE_PREFIX_PATH} "${CMAKE_PREFIX_PATH};${CMAKE_BINARY_DIR}/BZip2-build" )