FROM cbica/captk_centos7:devtoolset-4_superbuild

LABEL authors="CBICA_UPenn <software@cbica.upenn.edu>"

RUN yum update -y

RUN yum install git

RUN ls -l CaPTk_Libs/bin

ARG CMAKE_PREFIX_PATH=`pwd`/CaPTk_Libs/bin/ITK-build:`pwd`/CaPTk_Libs/bin/DCMTK-build
ENV CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH

RUN rm -rf CaPTk && git clone "https://github.com/sarthakpati/CaPTk.git"

RUN cd CaPTk && mkdir bin; \
    git pull origin master; \
    git submodule init && git submodule update; \
    git log -1

RUN cd CaPTk/bin; \
    cmake -DITK_DIR=../../CaPTk_Libs/bin/ITK-build -DDCMTK_DIR=../../CaPTk_Libs/bin/DCMTK-build -DCMAKE_INSTALL_PREFIX="./install/appdir/usr" -DBUILD_TESTING=OFF ..; \
    make -j2 && make install/strip; \
    cd .. && ./scripts/captk-pkg

# cleanup
RUN rm -rf CaPTk/bin/binaries_linux.zip && rm -rf CaPTk/bin/qt.zip

# define entry point
ENTRYPOINT ["/CaPTk/bin/install/appdir/usr/bin/CaPTk"]