FROM cbica/captk_centos7:devtoolset-4_superbuild

LABEL authors="CBICA_UPenn <software@cbica.upenn.edu>"

RUN yum update -y

RUN yum install git

RUN ls -l CaPTk_Libs/bin/ITK-build/*.cmake
RUN ls -l CaPTk_Libs/bin/DCMTK-build/*.cmake

ARG CMAKE_PREFIX_PATH=`pwd`/CaPTk_Libs/bin/ITK-build:`pwd`/CaPTk_Libs/bin/DCMTK-build
ENV CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
ARG DCMTK_DIR=`pwd`/CaPTk_Libs/bin/DCMTK-build
ENV DCMTK_DIR=$DCMTK_DIR

# installing CMake
RUN rm -rf /usr/bin/cmake; \
    wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh; \
    mkdir /opt/cmake; \
    sh cmake-3.12.4-Linux-x86_64.sh --prefix=/opt/cmake --skip-license; \
    ln -s /opt/cmake/bin/cmake /usr/bin/cmake; \
    rm -rf https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
    
RUN rm -rf CaPTk && git clone "https://github.com/sarthakpati/CaPTk.git" && ls -lt

RUN cd CaPTk && mkdir bin; \
    git pull origin master; \
    git submodule init && git submodule update; \
    git log -1

RUN cd CaPTk/bin; \
    if [ ! -d "`pwd`/externalApps" ] ; then wget https://github.com/CBICA/CaPTk/raw/master/binaries/precompiledApps/linux.zip -O binaries_linux.zip; fi ;
    cmake -DCMAKE_INSTALL_PREFIX="./install/appdir/usr" -DBUILD_TESTING=OFF ..; \
    make -j2 && make install/strip; \
    cd .. && ./scripts/captk-pkg

# cleanup
RUN rm -rf CaPTk/bin/binaries_linux.zip && rm -rf CaPTk/bin/qt.zip

# define entry point
ENTRYPOINT ["/CaPTk/bin/install/appdir/usr/bin/CaPTk"]